# Day 4 Assignment

# Level 1 - Basic

In [1]:
import numpy as np

In [15]:
nums=np.array([5, 10, 15, 20, 25, 30])
print(' 1D array:',nums)

 1D array: [ 5 10 15 20 25 30]

In [4]:
print("First element:",nums[0])
print("Last element",nums[-1])
print("Third element:",nums[2])

First element: 5
Last element 30
Third element: 15

In [14]:
arr=np.arange(0,20,2)
print('even numbers from 0 to 20 : ',arr)

even numbers from 0 to 20 :  [ 0  2  4  6  8 10 12 14 16 18]

In [12]:
Zeros=np.zeros(5)
print("1D array of five zeros:",Zeros)

1D array of five zeros: [0. 0. 0. 0. 0.]

In [16]:
Ones=np.ones(4)
print('four ones:',Ones)

four ones: [1. 1. 1. 1.]

In [17]:
n=np.array([100,230,202,203,232,544])
bonus=500
print("Daily steps + bonus :",n+bonus)

Daily steps + bonus : [ 600  730  702  703  732 1044]

In [22]:
import numpy as np

arr = np.linspace(0, 100, 5)
print('5 evenly spaced values between 0 and 100 : ',arr)

5 evenly spaced values between 0 and 100 :  [  0.  25.  50.  75. 100.]

# Level 2 — Intermediate

In [23]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [62, 74, 88],
    [91, 55, 70],
    [80, 68, 77]
])
print("Shape:", marks.shape)
print("Total elements:", marks.size)

Shape: (4, 3)
Total elements: 12

In [25]:
print('second student row:',marks[1])
print('first subjects column:',marks[:,1])

second student row: [62 74 88]
first subjects column: [85 74 55 68]

In [27]:
print('first two students and the last two subjects:',marks[0:2,1:])

first two students and the last two subjects: [[85 90]
 [74 88]]

In [35]:
nu=np.arange(12)
print(nu)
print('Reshape it into a 4 × 3 array :\n',nu.reshape(4,3))
print("Reshape it into a 3 × 4 array :\n",nu.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape it into a 4 × 3 array :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Reshape it into a 3 × 4 array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [38]:
student_avg = marks.mean(axis=1).round(2)
top_per_subject = marks.max(axis=0) 

print("Student Averages:", student_avg)
print("Top Score per Subject:", top_per_subject)

Student Averages: [84.33 74.67 72.   75.  ]
Top Score per Subject: [91 85 90]

In [37]:
import numpy as np

arr = np.array([12, 45, 7, 89, 34, 56, 23, 67])

print("Sum  :", arr.sum())
print("Mean :", arr.mean())
print("Min  :", arr.min())
print("Max  :", arr.max())
print("Std  :", arr.std().round(2))

Sum  : 333
Mean : 41.625
Min  : 7
Max  : 89
Std  : 26.43

In [40]:
test=np.array([10, 20, 30, 40, 50, 60])
print(test[1:4])
print(test[::2])

[20 30 40]
[10 30 50]

# Level 3 — Challenge

In [44]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row = np.array([10, 20, 30])
result = arr + row 
print("Broadcasting:\n",result)

Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

In [47]:
arr = np.array([10, 20, 30, 40, 50, 60])
standardised = (arr - arr.mean())/arr.std() 
print("Standardised:", standardised.round(2))
print("Mean after scaling:", standardised.mean().round(10))

Standardised: [-1.46 -0.88 -0.29  0.29  0.88  1.46]
Mean after scaling: 0.0

In [50]:
row=np.array([1,2,3,4,4])
col=np.array([[1],[2],[3],[3],[4]])
print("5x5 multiplication table:\n",row*col)

5x5 multiplication table:
 [[ 1  2  3  4  4]
 [ 2  4  6  8  8]
 [ 3  6  9 12 12]
 [ 3  6  9 12 12]
 [ 4  8 12 16 16]]

In [51]:
marks = np.array([78, 35, 90, 22, 55, 38, 88, 15, 60, 42])
print("Before:", marks)

marks[marks < 40] = 0 
print("After :", marks)

Before: [78 35 90 22 55 38 88 15 60 42]
After : [78  0 90  0 55  0 88  0 60 42]

In [52]:
image = np.array([
    [255, 128,  64,  32],
    [ 10, 200, 150,  80],
    [ 45, 170,  90, 220],
    [100,  55, 185, 240]
])
flat = image.flatten()             
normalised = flat / 255            

print("Flattened length:", len(flat))
print("Max after normalise:", normalised.max())
print("Normalised:", normalised.round(2))

Flattened length: 16
Max after normalise: 1.0
Normalised: [1.   0.5  0.25 0.13 0.04 0.78 0.59 0.31 0.18 0.67 0.35 0.86 0.39 0.22
 0.73 0.94]

In [55]:
sales = np.array([
    [200, 150, 300, 180],
    [220, 190, 280, 210],
    [250, 170, 320, 240]
])
print("Total per product:", sales.sum(axis=0))
print("Total per month  :", sales.sum(axis=1))
totals = sales.sum(axis=1)
best = max(totals)
print("Best selling month total: ₹", best)

Total per product: [670 510 900 630]
Total per month  : [830 900 980]
Best selling month total: ₹ 980

# Day 5-Assignment

# LEVEL 1 — BASIC

In [56]:
import pandas as pd
import numpy as np

In [72]:
data = {
    "Name": ["Aman", "Priya", "Rohit", "Neha", "Karan", "Sara", "Vikram", "Meera"],
    "Department": ["Sales", "IT", "IT", "HR", "Sales", "IT", "HR", "Sales"],
    "Age": [28, 34, 25, 41, 30, 38, 29, 33],
    "Salary": [42000, 68000, 40000, np.nan, 51000, 72000, 45000, 58000],
    "Experience": [3, 8, 2, 15, 5, np.nan, 4, 7]
}

df = pd.DataFrame(data)

df.to_csv("employee.csv", index=False)
print("CSV file created successfully!")
df

CSV file created successfully!

     Name Department  Age   Salary  Experience
0    Aman      Sales   28  42000.0         3.0
1   Priya         IT   34  68000.0         8.0
2   Rohit         IT   25  40000.0         2.0
3    Neha         HR   41      NaN        15.0
4   Karan      Sales   30  51000.0         5.0
5    Sara         IT   38  72000.0         NaN
6  Vikram         HR   29  45000.0         4.0
7   Meera      Sales   33  58000.0         7.0

In [61]:
sal=pd.Series([42000, 68000, 40000, 51000, 58000])
print(sal)

0    42000
1    68000
2    40000
3    51000
4    58000
dtype: int64

In [62]:
df.head(3)

    Name Department  Age   Salary  Experience
0   Aman      Sales   28  42000.0         3.0
1  Priya         IT   34  68000.0         8.0
2  Rohit         IT   25  40000.0         2.0

In [64]:
print("shape (row,col):",df.shape)

shape (row,col): (8, 5)

In [71]:
print("Name and salary:\n",df[['Name','Salary']])

Name and salary:
      Name   Salary
0    Aman  42000.0
1   Priya  68000.0
2   Rohit  40000.0
3    Neha      NaN
4   Karan  51000.0
5    Sara  72000.0
6  Vikram  45000.0
7   Meera  58000.0

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Department  8 non-null      object
 2   Age         8 non-null      int64
 3   Salary      7 non-null      float64
 4   Experience  7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 448.0+ bytes

# LEVEL 2 — INTERMEDIATE

In [75]:
print("employees who work in the “IT” department:\n",df[df['Department']=='IT'])

employees who work in the “IT” department:
     Name Department  Age   Salary  Experience
1  Priya         IT   34  68000.0         8.0
2  Rohit         IT   25  40000.0         2.0
5   Sara         IT   38  72000.0         NaN

In [76]:
print("all employees whose Age is greater than 30:\n",df[df['Age']>30])

all employees whose Age is greater than 30:
     Name Department  Age   Salary  Experience
1  Priya         IT   34  68000.0         8.0
3   Neha         HR   41      NaN        15.0
5   Sara         IT   38  72000.0         NaN
7  Meera      Sales   33  58000.0         7.0

In [77]:
print("“Sales” department who earn more than 50000:\n",df[(df['Department']=='Sales') & (df['Salary']>50000)])

“Sales” department who earn more than 50000:
     Name Department  Age   Salary  Experience
4  Karan      Sales   30  51000.0         5.0
7  Meera      Sales   33  58000.0         7.0

In [79]:
df.sort_values('Salary',ascending=False)

     Name Department  Age   Salary  Experience
5    Sara         IT   38  72000.0         NaN
1   Priya         IT   34  68000.0         8.0
7   Meera      Sales   33  58000.0         7.0
4   Karan      Sales   30  51000.0         5.0
6  Vikram         HR   29  45000.0         4.0
0    Aman      Sales   28  42000.0         3.0
2   Rohit         IT   25  40000.0         2.0
3    Neha         HR   41      NaN        15.0

In [80]:
df.isna().sum()

Name          0
Department    0
Age           0
Salary        1
Experience    1
dtype: int64

In [83]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df['Salary']

0    42000.000000
1    68000.000000
2    40000.000000
3    53714.285714
4    51000.000000
5    72000.000000
6    45000.000000
7    58000.000000
Name: Salary, dtype: float64

In [85]:
df['Experience']=df['Experience'].fillna(0)
df['Experience']

0     3.0
1     8.0
2     2.0
3    15.0
4     5.0
5     0.0
6     4.0
7     7.0
Name: Experience, dtype: float64

In [86]:
df['Bonus']=df['Salary']+df['Salary']*0.1

In [87]:
df.head()

    Name Department  Age        Salary  Experience         Bonus
0   Aman      Sales   28  42000.000000         3.0  46200.000000
1  Priya         IT   34  68000.000000         8.0  74800.000000
2  Rohit         IT   25  40000.000000         2.0  44000.000000
3   Neha         HR   41  53714.285714        15.0  59085.714286
4  Karan      Sales   30  51000.000000         5.0  56100.000000

# LEVEL 3 — CHALLENGE

In [89]:
df.groupby('Department')['Salary'].mean()

Department
HR       49357.142857
IT       60000.000000
Sales    50333.333333
Name: Salary, dtype: float64

In [90]:
df.groupby('Department')['Name'].count()

Department
HR       2
IT       3
Sales    3
Name: Name, dtype: int64

In [91]:
df['Salary'].max()

np.float64(72000.0)

In [92]:
df['Salary'].min()

np.float64(40000.0)

In [93]:
df['Age'].mean()

np.float64(32.25)

In [94]:
df.describe()

             Age        Salary  Experience         Bonus
count   8.000000      8.000000      8.0000      8.000000
mean   32.250000  53714.285714      5.5000  59085.714286
std     5.338539  11743.865094      4.6291  12918.251603
min    25.000000  40000.000000      0.0000  44000.000000
25%    28.750000  44250.000000      2.7500  48675.000000
50%    31.500000  52357.142857      4.5000  57592.857143
75%    35.000000  60500.000000      7.2500  66550.000000
max    41.000000  72000.000000     15.0000  79200.000000

Q 19.write 3–4 sentences answering — Which department looks the most experienced? Which earns the most on average? If you were hiring, what does this small dataset suggest, and why might such a small dataset be misleading for a real AI model?


Looking at the data, Engineering seems to be the most experienced department — 
most people there have been around for a while. 

When it comes to salary, HR actually takes the lead on average, 
which is a bit surprising but that's what the numbers say.

If I were hiring, I'd lean towards Engineering for technical roles 
since experience is already there. But honestly, this dataset is tiny —
we're talking about just a handful of people. 

One overpaid or super-experienced person can throw off the entire average. 
You wouldn't trust a weather forecast based on 5 days of data, 
so you definitely shouldn't train an AI model on this either.