# Day 1

In [1]:
name="ayush"
age=20
dept="CSEAIML"
cgpa=8.0
print("---student Profile---")
print("Name",name)
print("Age",age)
print("Dept",dept)
print("cgpa",cgpa)
print(type(cgpa))

---student Profile---
Name ayush
Age 20
Dept CSEAIML
cgpa 8.0
<class 'float'>

In [6]:
na=input("Enter name:")
print("hello",na)

hello ram

In [9]:
a=int(input("Enter the no.:"))
b=int(input("Enter the second no.:"))
print(f"sum {a+b}")
print(f"diff {a-b}")
print(f"product {a*b}")
print(f"reminder {a%b}")

sum 40
diff -20
product 300
reminder 10

In [10]:
a=int(input("enter the no."))
if a%2==0:
    print("even")
else:
    print("odd")

even

In [12]:
for i in range(0,100,2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98

In [13]:
a=int(input("enter the no."))
if a>90:
    print("first class pass")
elif a>60:
    print("pass hai bhai")
elif a>35:
    print("bas passs h bhai tu")
else:
    print("tu rehne de bhai ")

bas passs h bhai tu

In [17]:
n=input("enter the name:")
a=int(input("enter age:"))
print(f"Hello, my name is {n} and my age is {a}")

Hello, my name is ayush and my age is 20

In [18]:
a=75
if a>35:
    print("pass")
else:
    print("fail")

pass

In [23]:
i=int(input())
print(i)
if(i%3==0 and i%5==0):
    print("FIZZ BUZZ")
elif i%5==0:
    print("BUZZ")
elif i%3==0:
    print("FIZZ")
else: 
    print("invalid")

15
FIZZ BUZZ

In [24]:
s=input()
print(s)
b=s[::-1]
if s==b:
    print("Palindrome")
else:
    print("not palindrome")

mam
Palindrome

In [30]:
n=int(input())
print(n)
sum=0
while n>0:
    sum+=n%10
    n=n//10
print("sum",sum)

55
sum 10

In [31]:
a=int(input())
print("original:",a)
s=7
while a!=s:
    a=int(input())
    print("original:",a)
print("you got it")

original: 3
original: 4
original: 2
original: 6
original: 7
you got it

# Day 2

# Q1.Flatten a nested list

In [1]:
nested = [[1, 2], [3, 4], [5, 6]]

flat = []

for sublist in nested:
    for num in sublist:
        flat.append(num)

print(flat)

[1, 2, 3, 4, 5, 6]

# Q2.Word frequency counter

In [2]:
sentence = input("Enter a sentence: ")
print(sentence)

words = sentence.lower().split()
freq = {}

for word in words:
    freq[word] = freq.get(word, 0) + 1

print(freq)

{'hello': 2, 'world': 1, 'python': 1}

# Q3. calculator with function

In [3]:
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b

while True:
    print("\n1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Exit")

    choice = int(input("Enter choice: "))

    if choice == 5:
        break

    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))

    if choice == 1:
        print("Result:", add(a, b))
    elif choice == 2:
        print("Result:", subtract(a, b))
    elif choice == 3:
        print("Result:", multiply(a, b))
    elif choice == 4:
        print("Result:", divide(a, b))
    else:
        print("Invalid choice")

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Result: 1.5

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit

# Q4.Marks Anaylyzer

In [4]:
def analyze_marks(marks):
    minimum = min(marks)
    maximum = max(marks)
    average = sum(marks) / len(marks)

    passed = len([m for m in marks if m >= 40])
    pass_percentage = (passed / len(marks)) * 100

    grades = []
    for m in marks:
        if m >= 90:
            grades.append("A")
        elif m >= 75:
            grades.append("B")
        elif m >= 60:
            grades.append("C")
        elif m >= 40:
            grades.append("D")
        else:
            grades.append("F")

    return minimum, maximum, average, pass_percentage, grades

marks = [85, 92, 67, 45, 30]

result = analyze_marks(marks)

print("Min:", result[0])
print("Max:", result[1])
print("Average:", result[2])
print("Pass %:", result[3])
print("Grades:", result[4])

Min: 30
Max: 92
Average: 63.8
Pass %: 80.0
Grades: ['B', 'A', 'C', 'D', 'F']

# Q4.Top N-student

In [5]:
students = {
    "Ayush": 95,
    "Rahul": 85,
    "Aman": 90
}

sorted_students = sorted(students.items(),
                         key=lambda x: x[1],
                         reverse=True)

print(sorted_students[:2])

[('Ayush', 95), ('Aman', 90)]

# Day 3

In [7]:
import math
print(math.sqrt(16))
print(math.pi)

4.0
3.141592653589793

In [9]:
import numpy as np
import pandas as pd

In [14]:
print(math.ceil(4.2))

5

In [17]:
try:
    n=int(input("enter the no."))
    r=10/n
    print("result",r)
except ZeroDivisionError:
    print("error")
except ValueError:
    print("value eroor")
finally:
    print("completed")

value eroor
completed

In [33]:
def add(a, b):
    return a + b

def subtract(a, b): 
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b

try:
    a = int(input("Enter a: "))
    print(a)
    b = int(input("Enter b: "))
    print(b)
    print(f"Add: {add(a,b)}")
    print(f"Subtract: {subtract(a,b)}")
    print(f"Multiply: {multiply(a,b)}")
    print(f"Divide: {divide(a,b)}")
except ZeroDivisionError:
    print("divide by 0 error")
except ValueError:
    print("Value Error")

12
0
Add: 12
Subtract: 12
Multiply: 0
divide by 0 error

In [39]:
with open("student.txt","r") as f:
    c=f.read()
    print(c)
    f.seek(0)
    list_of_lines=f.readlines()
    print(list_of_lines)

ayush
raman
amana
anna
['ayush\n', 'raman\n', 'amana\n', 'anna']

In [35]:
with open("student1.txt","w") as f:
    c=f.write("ayush")

In [44]:
with open("student1.txt","a") as f:
    c=f.write("vishnoi")

In [46]:
with open("student1.txt","r") as f:
    f.seek(0)
    c=f.read()
    print(c)

ayush vishnoivishnoi

# convert dictonary into json format

In [51]:
import json
stu_dic={'name':'ayush','score':49,'enrolled':True}
json_sring=json.dumps(stu_dic,indent=4)
print(json_sring)

{
    "name": "ayush",
    "score": 49,
    "enrolled": true
}

# Convert json format into dictionary

In [56]:
import json
json_sring='{"name":"ayush","score":49,"enrolled":true}'
dic=json.loads(json_sring)
print(dic)

{'name': 'ayush', 'score': 49, 'enrolled': True}

In [68]:
import json
stu_dic={'name':'ayush','score':49,'enrolled':True,'stu_id':18}
json_sring=json.dumps(stu_dic,indent=4)
print(json_sring)
data=json.loads(json_sring)
print('\n')
print( "name:",data['name'])
print("score:",data['score'])
print("enrolled or not:",data['enrolled'])
print("student id:",data['stu_id'])

{
    "name": "ayush",
    "score": 49,
    "enrolled": true,
    "stu_id": 18
}


name: ayush
score: 49
enrolled or not: True
student id: 18

# oops basics -classes & object

In [76]:
class student:
    def __init__(self,name,roll,branch):
        self.name=name
        self.roll=roll
        self.branch=branch
s1=student('ayush',18,'cseaiml')
s1=student('ayush',15,'cseaiml')

<__main__.student object at 0x112f5b550>

# Q1 Modules challenge

In [85]:
import random
rand=[]

for i in range(10):
    x=random.uniform(50,100)
    rand.append(x)
print(rand)
sumi=0
maxi=rand[0]
mini=rand[0]
for num in rand:
    if num > maxi:
        maxi = num
    if num < mini:
        mini = num
    sumi += num
print("Max:",maxi)
print("Min:",mini)
print("Mean:",sumi/10.0)

[53.90401379773917, 71.80592768136017, 89.84681801986028, 84.88425989427418, 97.35685972997172, 95.5058015787898, 87.07637207708534, 58.68837419156248, 73.45046194477227, 59.9337639124188]
Max: 97.35685972997172
Min: 53.90401379773917
Mean: 77.24526528278344

# Q2 File Handling challenge

In [103]:
students = [['ayush', 34], ['aman', 33], ['raman', 30], ['yash', 14], ['raj', 24]]
with open("student.txt", "w") as f:
    for s in students:
        f.write(f"{s[0]} ,{s[1]}\n")

In [112]:
with open("student.txt", "r") as f:
    maxi=0
    avg=0
    n=0
    for line in f:
        name, score = line.strip().split(",")
        score=int(score)
        n=n+1
        avg+=score
        if maxi<score:
            maxi=score
            top_name=name
print("Average:",avg/n)
print("Top scorer:",top_name)

Average: 27.0
Top scorer: ayush

# Q3 json challenge

In [126]:
import json
ai_model_config = {"model_name": "gpt-4","version": "1.0","max_tokens": 8192,"temperature": 0.7,"provider": "openai",}
json_sring=json.dumps(ai_model_config,indent=4)

with open("config.json", "w") as f:
    json.dump(ai_model_config, f, indent=4)
print("File created")

print(json_sring)
data=json.loads(json_sring)
print("\n")
print( "Model name:",data['model_name'])
print("Version:",data['version'])
print("Max tokens:",data['max_tokens'])
print("Temperature:",data['temperature'])
print("Provider:",data['provider'])

File created
{
    "model_name": "gpt-4",
    "version": "1.0",
    "max_tokens": 8192,
    "temperature": 0.7,
    "provider": "openai"
}


Model name: gpt-4
Version: 1.0
Max tokens: 8192
Temperature: 0.7
Provider: openai

# Q4 oop challenge

In [125]:
class BankAccount:
    def __init__(self, owner, balance=0):
        self.owner = owner
        self.balance = balance
    def deposit(self, amount):
            self.balance += amount
            print(f"Deposited ₹{amount} -> Balance: ₹{self.balance}")
    def withdraw(self, amount):
        try:
            if amount > self.balance:
                raise Exception("Overdraft")
            self.balance -= amount
            print("Withdrawn:", amount)
        except Exception as e:
            print("Error:", e)
    def get_balance(self):
        print(f"Balance: ₹{self.balance}")
        
acc = BankAccount("Ayush", 1000)
acc.deposit(500)
acc.withdraw(200)
acc.get_balance()
acc.withdraw(5000)

Deposited ₹500 -> Balance: ₹1500
Withdrawn: 200
Balance: ₹1300
Error: Overdraft

# Day 4

# Numpy

In [127]:
import numpy as np

In [134]:
marks=np.array([78,85,90,67])
ages=np.array([20,21,20,20,22])

In [137]:
print(marks)
print(ages.shape)
print(marks.dtype)

[78 85 90 67]
(5,)
int64

In [138]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Slicing

for slicing --- arr[row,col]

for range with specific row or column---arr[strat row : end row , strat column : end column]

In [139]:
arr[1,2]

np.int64(6)

In [141]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


for dimension

In [142]:
arr.ndim

2

convert into 1d to 2d

In [143]:
data=np.arange(12)

In [144]:
data.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
data.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [149]:
data.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [147]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

convert 2d to 1d

In [148]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
a=np.array([1,2,3])
b=np.array([2,6,3])
print(a+b)
a-b

[3 8 6]

array([-1, -4,  0])

Broadcasting

In [156]:
a+5

array([6, 7, 8])

In [157]:
a**2

array([1, 4, 9])

a.sum()
a.min()
a.std()
a.max()

In [159]:
a.std()

np.float64(0.816496580927726)

sum variation---axis=0 sum up all the row

             ---axis=1 sum up all the column

In [164]:
print(a.sum(axis=0))
print(arr.sum(axis=1))

6
[ 6 15 24]

In [177]:
marks=np.array([72,88,95,64,79,90,58])
c=marks.mean()
print(marks.mean())
print(marks.max())
print(marks.min())
for i in marks:
    if i>marks.mean():
        print("greater than average",i)
        
g=marks>c
print(g)

78.0
95
58
greater than average 88
greater than average 95
greater than average 79
greater than average 90
[False  True  True False  True  True False]

# Rules

1. shape(3,) fits each row of (2,3)

2. (2,3) +(1,3) will fit but (2,3) +(2,) will not

In [179]:
m=np.array([[12,3,3],
            [3,2,3]])
row=np.array([12,12,23])
m+row

array([[24, 15, 26],
       [15, 14, 26]])

In [180]:
marks=np.array([23,21,3,23,32])
print("Mean:",marks.mean())
print("Standard deviation:",marks.std())

Mean: 20.4
Standard deviation: 9.499473669630333

In [181]:
m=np.array([[12,3,3],
            [3,2,3]])
m.flatten()

array([12,  3,  3,  3,  2,  3])

In [200]:
l=np.array([[12,53,43],
            [33,32,33]])
for i in range(len(l)):
    for j in range(len(l[0])):
        if (l[i][j]<40):
            l[i][j]=0
print(l)

[[ 0 53 43]
 [ 0  0  0]]

In [198]:
row=np.array([1,2,3,4,5])
col=np.array([[5],[4],[3],[2],[2]])
mul=row*col
print(mul)
print("shape:",mul.shape)

[[ 5 10 15 20 25]
 [ 4  8 12 16 20]
 [ 3  6  9 12 15]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
shape: (5, 5)

# Pandas

In [201]:
import pandas as pd

In [203]:
student={
    'Name':['rahul','sneha','arjun','divya','karan'],
    'Age':[21,22,21,23,22],
    'Marks':[78,91,64,88,55],
    'city':['delhi','pune','jaipur','delhi','pune']
}
df=pd.DataFrame(student)
df

    Name  Age  Marks    city
0  rahul   21     78   delhi
1  sneha   22     91    pune
2  arjun   21     64  jaipur
3  divya   23     88   delhi
4  karan   22     55    pune

In [207]:
mark=pd.Series([78,33,29,94,93],name='Marks')
print(mark)
print(type(mark))

0    78
1    33
2    29
3    94
4    93
Name: Marks, dtype: int64
<class 'pandas.core.series.Series'>

In [208]:
temp=pd.Series([78,33,29,94,93],name='temp')
print(temp.mean())

65.4

In [223]:
student=pd.DataFrame({
    'Name':['rahul','sneha','arjun','divya','karan'],
    'Age':[21,22,'null',23,'null'],
    'Marks':[78,91,64,88,55],
    'city':['delhi','pune','jaipur','delhi','pune']
})
student.to_csv('student.csv',index=False)
df=pd.read_csv('student.csv')
df.head()

    Name   Age  Marks    city
0  rahul  21.0     78   delhi
1  sneha  22.0     91    pune
2  arjun   NaN     64  jaipur
3  divya  23.0     88   delhi
4  karan   NaN     55    pune

In [215]:
df.shape

(5, 4)

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

In [217]:
df.describe()

            Age      Marks
count   5.00000   5.000000
mean   21.80000  75.200000
std     0.83666  15.449919
min    21.00000  55.000000
25%    21.00000  64.000000
50%    22.00000  78.000000
75%    22.00000  88.000000
max    23.00000  91.000000

In [218]:
df.head()

    Name  Age  Marks    city
0  rahul   21     78   delhi
1  sneha   22     91    pune
2  arjun   21     64  jaipur
3  divya   23     88   delhi
4  karan   22     55    pune

In [219]:
df.shape

(5, 4)

In [220]:
df.tail(2)

    Name  Age  Marks   city
3  divya   23     88  delhi
4  karan   22     55   pune

In [221]:
df[df['Age']>22]

    Name  Age  Marks   city
3  divya   23     88  delhi

In [222]:
df.sort_values('Age',ascending=True)

    Name  Age  Marks    city
0  rahul   21     78   delhi
2  arjun   21     64  jaipur
1  sneha   22     91    pune
4  karan   22     55    pune
3  divya   23     88   delhi

In [224]:
df.isnull().sum()

Name     0
Age      2
Marks    0
city     0
dtype: int64

In [225]:
df.head()

    Name   Age  Marks    city
0  rahul  21.0     78   delhi
1  sneha  22.0     91    pune
2  arjun   NaN     64  jaipur
3  divya  23.0     88   delhi
4  karan   NaN     55    pune

In [226]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [227]:
df.head()

    Name   Age  Marks    city
0  rahul  21.0     78   delhi
1  sneha  22.0     91    pune
2  arjun  22.0     64  jaipur
3  divya  23.0     88   delhi
4  karan  22.0     55    pune

In [228]:
employee = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry', 'Isla', 'Jack'],
    'Age': [30, 25, 35, 28, 40, 32, 27, 45, 29, 38],
    'Salary': [70000, None, 90000, 60000, 110000, None, 55000, None, 65000, 95000],
    'Experience': [6, 3, None, 4, 12, 7, 2, 10, None, 8]
})
employee.to_csv('employees.csv', index=False)
df = pd.read_csv('employees.csv')
print("Original:\n", df.head(10))

Original:
       Name  Age    Salary  Experience
0    Alice   30   70000.0         6.0
1      Bob   25       NaN         3.0
2  Charlie   35   90000.0         NaN
3    Diana   28   60000.0         4.0
4      Eve   40  110000.0        12.0
5    Frank   32       NaN         7.0
6    Grace   27   55000.0         2.0
7    Henry   45       NaN        10.0
8     Isla   29   65000.0         NaN
9     Jack   38   95000.0         8.0

In [229]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Experience'] = df['Experience'].fillna(0)

In [230]:
df.head()

      Name  Age         Salary  Experience
0    Alice   30   70000.000000         6.0
1      Bob   25   77857.142857         3.0
2  Charlie   35   90000.000000         0.0
3    Diana   28   60000.000000         4.0
4      Eve   40  110000.000000        12.0

In [232]:
seniority = []
for x in df['Experience']:
    if x >= 5:
        seniority.append('Senior')
    else:
        seniority.append('Junior')

df['Seniority'] = seniority

In [233]:
print("\nCleaned Data:\n", df)
print("\nAverage Salary:\n", df.groupby('Seniority')['Salary'].mean().round(2))

Cleaned Data:
       Name  Age         Salary  Experience Seniority
0    Alice   30   70000.000000         6.0    Senior
1      Bob   25   77857.142857         3.0    Junior
2  Charlie   35   90000.000000         0.0    Junior
3    Diana   28   60000.000000         4.0    Junior
4      Eve   40  110000.000000        12.0    Senior
5    Frank   32   77857.142857         7.0    Senior
6    Grace   27   55000.000000         2.0    Junior
7    Henry   45   77857.142857        10.0    Senior
8     Isla   29   65000.000000         0.0    Junior
9     Jack   38   95000.000000         8.0    Senior

Average Salary:
 Seniority
Junior    69571.43
Senior    86142.86
Name: Salary, dtype: float64